SELECT
SUBSTR(LPAD(SCA.TIME_PICKED, 6),1,2) ||'-'|| CASE
WHEN TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) <=15 THEN 1
WHEN TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) > 15 AND TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) <= 30 THEN 2
WHEN TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) >30 AND TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) <= 45 THEN 3
ELSE 4
END AS HOUR_QUARTER
, SUM(SCA.QTY_PICKED) AS QTY

FROM
 GOFSLIVE_GOFOS2.SCANSTAT_LINE SCA
,(
SELECT BATCHNR,SET_OUTBOUNDLINE
FROM GOFSLIVE_GOFOS2.BATCH_STAT
WHERE BEDRYFNR = 130

UNION ALL

SELECT BATCHNR,SET_OUTBOUNDLINE
FROM GOFSLIVE_GOFOS2.BATCH_STAT_HST
WHERE BEDRYFNR = 130

)BAT2 

WHERE SCA.BATCHNR = BAT2.BATCHNR
AND BAT2.SET_OUTBOUNDLINE IN ('Z', 'Y', '1', '2', 'L', 'N')
AND SCA.DATE_PICKED = TO_NUMBER(TO_CHAR(SYSDATE, 'YYYYMMDD'))

GROUP BY 
SUBSTR(LPAD(SCA.TIME_PICKED, 6),1,2) ||'-'|| CASE
WHEN TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) <=15 THEN 1
WHEN TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) > 15 AND TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) <= 30 THEN 2
WHEN TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) >30 AND TO_NUMBER(SUBSTR(LPAD(SCA.TIME_PICKED, 6),3,2)) <= 45 THEN 3
ELSE 4
END 