SELECT  DISTINCT
TO_NUMBER(TO_CHAR(V_D5."DateTime", 'HH24' )) AS "Hour"
, SUM(V_D1."Quantity") OVER (PARTITION BY TO_CHAR(V_D5."DateTime", 'HH24' ) ) AS QTY



FROM     
REPORT.V_DATAPACKING_SHIPMENT V_D4, 
REPORT.V_DATAPACKING_SHIPMENTLINE V_D1, 
(  
	SELECT V_D2."ShipmentLineId", max(V_D2."CurrentHistoryId") as MAX_HISTORY_ID
	from
	REPORT.V_DATAPACKING_SHIPMENTLINEITEM V_D2
	group by V_D2."ShipmentLineId"
)
V_D2 ,
REPORT.V_DATAPACKING_SHIPLINEHIS V_D5 



WHERE V_D4."Id"=V_D1."Shipment"   
AND V_D1."Id"=V_D2."ShipmentLineId" 
and V_D2.MAX_HISTORY_ID =V_D5."Id"
AND V_D4."OrderType" IN ('VAS','B2S')
AND V_D5."DateTime" >  trunc(SYSDATE)

ORDER BY TO_NUMBER(TO_CHAR(V_D5."DateTime", 'HH24' )) ASC