SELECT DISTINCT
MAIN.*, BAT1.SET_OUTBOUNDLINE
FROM 
(

SELECT DISTINCT
PIC.PICKLYSTNR
, ORD.ORDERTYPE
, SUM(PIC.AANTAL) AS QTY



FROM GOFSLIVE_GOFOS2.PICKLIST_LIN PIC
, GOFSLIVE_GOFOS2.ORDERHDR_EXT ORD


WHERE PIC.ORDERNR = ORD.ORDERNR
AND ORD.IMPORT_DATUM = TO_CHAR(SYSDATE, 'YYYYMMDD')
AND ORD.ORDERTYPE IN ('B2S', 'VAS')
AND PIC.LOKATIENR NOT LIKE '35899%'

GROUP BY PIC.PICKLYSTNR
, ORD.ORDERTYPE


)MAIN
LEFT OUTER JOIN GOFSLIVE_GOFOS2.BATCH_HDR BAT ON MAIN.PICKLYSTNR = BAT.PICKLYSTNR
LEFT OUTER JOIN GOFSLIVE_GOFOS2.BATCH_STAT BAT1 ON BAT.BATCHNR = BAT1.BATCHNR

WHERE BAT1.SET_OUTBOUNDLINE NOT IN ('N')